package com.dumchykov.socialnetworkdemo.ui.util

import androidx.compose.foundation.text.selection.TextSelectionColors
import androidx.compose.material3.TextFieldColors
import androidx.compose.ui.graphics.Color
import com.dumchykov.socialnetworkdemo.ui.theme.White

fun customTextFieldsColors(
    focusedTextColor: Color = White,
    unfocusedTextColor: Color = White,
    disabledTextColor: Color = White,
    errorTextColor: Color = White,
    focusedContainerColor: Color = Color.Transparent,
    unfocusedContainerColor: Color = Color.Transparent,
    disabledContainerColor: Color = Color.Transparent,
    errorContainerColor: Color = Color.Transparent,
    cursorColor: Color = White,
    errorCursorColor: Color = White,
    selectionColors: TextSelectionColors = TextSelectionColors(White, White.copy(alpha = 0.4f)),
    focusedIndicatorColor: Color = White,
    unfocusedIndicatorColor: Color = White,
    disabledIndicatorColor: Color = White,
    errorIndicatorColor: Color = White,
    focusedLeadingIconColor: Color = White,
    unfocusedLeadingIconColor: Color = White,
    disabledLeadingIconColor: Color = White,
    errorLeadingIconColor: Color = White,
    focusedTrailingIconColor: Color = White,
    unfocusedTrailingIconColor: Color = White,
    disabledTrailingIconColor: Color = White,
    errorTrailingIconColor: Color = White,
    focusedLabelColor: Color = White,
    unfocusedLabelColor: Color = White,
    disabledLabelColor: Color = White,
    errorLabelColor: Color = White,
    focusedPlaceholderColor: Color = White,
    unfocusedPlaceholderColor: Color = White,
    disabledPlaceholderColor: Color = White,
    errorPlaceholderColor: Color = White,
    focusedSupportingTextColor: Color = White,
    unfocusedSupportingTextColor: Color = White,
    disabledSupportingTextColor: Color = White,
    errorSupportingTextColor: Color = Color.Red,
    focusedPrefixColor: Color = White,
    unfocusedPrefixColor: Color = White,
    disabledPrefixColor: Color = White,
    errorPrefixColor: Color = White,
    focusedSuffixColor: Color = White,
    unfocusedSuffixColor: Color = White,
    disabledSuffixColor: Color = White,
    errorSuffixColor: Color = White,
): TextFieldColors {
    return TextFieldColors(
        focusedTextColor,
        unfocusedTextColor,
        disabledTextColor,
        errorTextColor,
        focusedContainerColor,
        unfocusedContainerColor,
        disabledContainerColor,
        errorContainerColor,
        cursorColor,
        errorCursorColor,
        selectionColors,
        focusedIndicatorColor,
        unfocusedIndicatorColor,
        disabledIndicatorColor,
        errorIndicatorColor,
        focusedLeadingIconColor,
        unfocusedLeadingIconColor,
        disabledLeadingIconColor,
        errorLeadingIconColor,
        focusedTrailingIconColor,
        unfocusedTrailingIconColor,
        disabledTrailingIconColor,
        errorTrailingIconColor,
        focusedLabelColor,
        unfocusedLabelColor,
        disabledLabelColor,
        errorLabelColor,
        focusedPlaceholderColor,
        unfocusedPlaceholderColor,
        disabledPlaceholderColor,
        errorPlaceholderColor,
        focusedSupportingTextColor,
        unfocusedSupportingTextColor,
        disabledSupportingTextColor,
        errorSupportingTextColor,
        focusedPrefixColor,
        unfocusedPrefixColor,
        disabledPrefixColor,
        errorPrefixColor,
        focusedSuffixColor,
        unfocusedSuffixColor,
        disabledSuffixColor,
        errorSuffixColor
    )
}